// Downloads the web fonts and writes public/fonts/fonts.css, so the site serves
// them itself instead of linking fonts.googleapis.com.  Run with `npm run fonts`.
//
// Why: Google Fonts is two origins on the critical path — the stylesheet on
// fonts.googleapis.com and the files on fonts.gstatic.com, in series, because the
// file URLs are only discoverable after the stylesheet parses. Measured cold from
// Dubai that is 440ms + 477ms of DNS+TLS before a single glyph is requested. Both
// disappear when the CSS and the woff2 come from our own origin, on a connection
// the HTML has already opened.
//
// It also switches DM Sans from five static weights to the variable font:
//   static    12 files   505 KB total   (a latin page pulls ~5 of them)
//   variable   4 files   130 KB total   (a latin page pulls 1, 62.7 KB)
// and the variable axis covers 100..1000, so fontWeight: 800 — used in 79 places
// and previously synthesised by the browser, because the request stopped at 700 —
// now renders as the real weight.
//
// Keeping unicode-range intact matters: the browser only fetches the latin-ext
// file if the page actually contains those characters.
import { writeFileSync, mkdirSync } from 'node:fs'
import { join, dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const OUT_DIR = join(ROOT, 'public/fonts')

// A modern UA is required — Google serves ttf to anything it does not recognise.
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36'
// Every family the site uses. DM Sans/Serif come from index.css; Sora, Manrope
// and Playfair Display were each pulled in by an inline @import inside a page
// component — an @import is invisible to the preload scanner, so those pages
// could not start the download until their CSS had been parsed.
// Families must be listed alphabetically — the css2 API returns 400 otherwise.
const CSS_URL = 'https://fonts.googleapis.com/css2'
  + '?family=DM+Sans:opsz,wght@9..40,100..1000'
  + '&family=DM+Serif+Display'
  + '&family=Manrope:wght@400;500;600;700'
  + '&family=Playfair+Display:wght@600;700'
  + '&family=Sora:wght@400;500;600;700;800'
  + '&display=swap'

let css = await fetch(CSS_URL, { headers: { 'User-Agent': UA } }).then((r) => {
  if (!r.ok) throw new Error(`Google Fonts CSS: HTTP ${r.status}`)
  return r.text()
})

const urls = [...new Set([...css.matchAll(/https:\/\/fonts\.gstatic\.com\/[^)"']+/g)].map((m) => m[0]))]
if (!urls.length) { console.error('! no font files found in the stylesheet'); process.exit(1) }
if (!urls.every((u) => u.endsWith('.woff2'))) {
  console.error('! got a non-woff2 file — the User-Agent is probably not being honoured')
  process.exit(1)
}

mkdirSync(OUT_DIR, { recursive: true })
let total = 0
for (const url of urls) {
  const name = url.split('/').pop()
  const buf = Buffer.from(await fetch(url).then((r) => {
    if (!r.ok) throw new Error(`${name}: HTTP ${r.status}`)
    return r.arrayBuffer()
  }))
  writeFileSync(join(OUT_DIR, name), buf)
  total += buf.length
  css = css.split(url).join(`/fonts/${name}`)
}

const header = `/* GENERATED by scripts/gen-fonts.mjs. Do not edit by hand — run \`npm run fonts\`.\n   Source: ${CSS_URL} */\n`
writeFileSync(join(OUT_DIR, 'fonts.css'), header + css)
console.log(`Wrote public/fonts/fonts.css + ${urls.length} woff2 (${(total / 1024).toFixed(1)} KB total).`)
